##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [2.27.0] date: [Fri May 11 17:38:48 MSK 2018] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = usb_test


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# openocd debug bulid?
OPENOCD_DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# source path
SOURCES_DIR =  \
Application/User/Src/usbd_cdc_if.c \
Drivers \
Application/User \
Application/User/Src/usbd_desc.c \
Application/User/Src/usb_device.c \
Application/User/Src/usbd_conf.c \
Middlewares/USB_Device_Library \
Application \
Application/User/Src/main.c \
Middlewares \
Drivers/STM32F4xx_HAL_Driver \
Drivers/CMSIS \
Application/User/Src/stm32f4xx_it.c \
Application/User/Src/stm32f4xx_hal_msp.c \
Application/User/Src \
 \
Utilities/Log \
Drivers/BSP/STM32F429I-Discovery \
Drivers/BSP/Components/stmpe811 \
Drivers/BSP/Components/ili9341 \

# firmware library path
PERIFLIB_PATH = 

# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c \
Src/main.c \
Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c \
Src/stm32f4xx_hal_msp.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Src/system_stm32f4xx.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fmc.c \
Src/usb_device.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Src/usbd_conf.c \
Src/usbd_cdc_if.c \
Src/stm32f4xx_it.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sdram.c \
Src/usbd_desc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_ltdc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c \
Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c \
Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dsi.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma2d.c \
Src/dma2d.c \
Src/i2c.c \
Src/spi.c \
Src/usart.c \
Src/ltdc.c \
Src/fmc.c \
Src/gpio.c \
 \
Src/ht_runtime.c \
Src/ht_scheduled_funs.c \
 \
SW4STM32/syscalls.c \
Utilities/Log/lcd_log.c \
Drivers/BSP/STM32F429I-Discovery/stm32f429i_discovery.c \
Drivers/BSP/STM32F429I-Discovery/stm32f429i_discovery_eeprom.c \
Drivers/BSP/STM32F429I-Discovery/stm32f429i_discovery_gyroscope.c \
Drivers/BSP/STM32F429I-Discovery/stm32f429i_discovery_io.c \
Drivers/BSP/STM32F429I-Discovery/stm32f429i_discovery_lcd.c \
Drivers/BSP/STM32F429I-Discovery/stm32f429i_discovery_sdram.c \
Drivers/BSP/STM32F429I-Discovery/stm32f429i_discovery_ts.c \
Drivers/BSP/Components/stmpe811/stmpe811.c \
Drivers/BSP/Components/ili9341/ili9341.c \
Drivers/BSP/Components/l3gd20/l3gd20.c

#Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \


# ASM sources
ASM_SOURCES =  \
./SW4STM32/startup_stm32f429xx.s


######################################
# firmware library
######################################
PERIFLIB_SOURCES = 


#######################################
# binaries
#######################################
BINPATH = /usr/bin
PREFIX = arm-none-eabi-
CC = $(BINPATH)/$(PREFIX)gcc
AS = $(BINPATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(BINPATH)/$(PREFIX)objcopy
AR = $(BINPATH)/$(PREFIX)ar
SZ = $(BINPATH)/$(PREFIX)size
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F429xx

# Debug specific definitions for semihosting
# ifeq ($(OPENOCD_DEBUG), 1)
# C_DEFS += -DUSE_DBPRINTF
# endif

# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-IInc \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc \
-IMiddlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Include \
-IUtilities/Log \
-IUtilities/Fonts \
-IDrivers/BSP/STM32F429I-Discovery \
-IDrivers/BSP/Components/Common \
-IDrivers/BSP/Components/stmpe811 \
-IDrivers/BSP/Components/ili9341 \
-IDrivers/BSP/Components/l3gd20


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F429ZITx_FLASH.ld

LIBDIR = 
LDFLAGS_BASE = $(MCU) -T$(LDSCRIPT) $(LIBDIR) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections
# Default libraries & specs
LDFLAGS = $(LDFLAGS_BASE) -specs=nano.specs -lc -lm -lnosys

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin

#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR .dep $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(shell mkdir .dep 2>/dev/null) $(wildcard .dep/*)

#######################################
# Program & Debug Target
#######################################

# Don't forget to
#   remove duplicate sources in C_SOURCES.
#   fix BINPATH
#   adjust DEBUG=1 & OPT=0g options

# Enable Semihosting
LDFLAGS_OPENOCD = $(LDFLAGS_BASE) -specs=rdimon.specs -lc -lrdimon
# ifeq ($(OPENOCD_DEBUG), 1)
#     LDFLAGS = $(LDFLAGS_OPENOCD)
# endif

# debug with openocd
debug: debug_elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin

# Same target as $(BUILD_DIR)/$(TARGET).elf but using different LDFLAGS
debug_elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS_OPENOCD) -o $(BUILD_DIR)/$(TARGET).elf
	$(SZ) $(BUILD_DIR)/$(TARGET).elf


OPENOCD ?= openocd
OPENOCD_DIR="/usr/share/openocd"
OPENOCD_SCRIPTS_DIR="${OPENOCD_DIR}/scripts"
OPENOCD_FLAGS = -f interface/stlink-v2-1.cfg -f board/stm32f429discovery.cfg

openocd:
	$(OPENOCD) -s $(OPENOCD_SCRIPTS_DIR) $(OPENOCD_FLAGS)

program: #all
	$(OPENOCD) -s $(OPENOCD_SCRIPTS_DIR) $(OPENOCD_FLAGS) \
	           -c "program $(BUILD_DIR)/$(TARGET).elf verify reset" \
	           -c "shutdown"

# *** EOF ***

